# Generated by Django 4.1 on 2022-08-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Entrega", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="familia2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=30)),
                ("Edad", models.ImageField(upload_to="")),
                ("cumple", models.DateField()),
            ],
        ),
        migrations.DeleteModel(name="familia",),
    ]
