# Generated by Django 4.1 on 2022-08-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Entrega", "0003_familia_delete_familia2"),
    ]

    operations = [
        migrations.CreateModel(
            name="familia2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.CharField(max_length=30)),
                ("edad", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(name="familia",),
    ]
